---
name: Build disk image
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 1 * * TUE"
  workflow_dispatch:

jobs:
  build_release:
    name: Build and release disk image
    permissions:
      contents: read
      packages: read
      id-token: write
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        platform: ["amd64"]
    runs-on: ${{ matrix.platform == 'amd64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Maximize build space
        if: inputs.platform != 'arm64'
        uses: ublue-os/remove-unwanted-software@cc0becac701cf642c8f0a6613bbdaf5dc36b259e # v9
        with:
          remove-codeql: true

      - name: Build ISO
        id: build-iso
        uses: osbuild/bootc-image-builder-action@main
        with:
          config-file: ./iso.toml
          image: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          types: anaconda-iso
          rootfs: btrfs
          additional-args: --use-librepo=True

      - name: Upload Artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.platform }}
          path: ${{ steps.build-iso.outputs.output-directory }}
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
          overwrite: true

      - name: Upload to S3
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        shell: bash
        env:
          RCLONE_CONFIG_S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          RCLONE_CONFIG_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          RCLONE_CONFIG_S3_PROVIDER: ${{ secrets.S3_PROVIDER }}
          RCLONE_CONFIG_S3_REGION: ${{ secrets.S3_REGION }}
          RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_S3_TYPE: s3
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          SOURCE_DIR: ${{ steps.build-iso.outputs.output-directory }}
        run: |
          sudo apt update -y
          sudo apt install -y rclone
          rclone copy "${SOURCE_DIR}" "S3:${S3_BUCKET_NAME}"
